# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a9739ede9921c5c265a9d65812cd15db55b1c87cb60bdab50c52e4a3f701817d6675bcb896eff93cab6e6de222d6d0d4a631c677752bdea038f6a0705f7a24

test:
  secret_key_base: d9edc1f1d1bba503adb3b6e96a78b156a3d36de002d29c33a078e01c9b13266a409d6c4ef25d9deda6a707d035a166a933a006e13a7739ebcbfad86e56aa451e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
